name: Build Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - ksu-next

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 1

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth 1
          git submodule foreach --recursive '
            echo "Unshallowing submodule: $name"
            git fetch --unshallow || git fetch
            git checkout -f
          '

      - name: Cache Toolchains
        uses: actions/cache@v5
        id: cache-toolchains
        with:
          path: toolchain/
          key: ${{ runner.os }}-toolchains-r530567

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex kmod cpio libelf-dev gcc-aarch64-linux-gnu

      - name: Compile Kernel
        run: |
          chmod +x ./build_kernel_zip.sh
          ./build_kernel_zip.sh || true

      # cause we continue on error (it was erroring on success so this is better i guess)
      - name: Check if kernel zip exists 
        run: |
          zips=( *.zip )
          if [ ! -e "${zips[0]}" ]; then
              exit 1
          fi

      - name: Set sha_short env variable
        run: echo "sha_short=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        
      - name: Upload Kernel
        uses: actions/upload-artifact@v7
        with:
          name: "a52s_oneui_ksu-next-${{ env.sha_short }}"
          path: "*.zip"
          compression-level: 0

      - name: Upload build config
        uses: actions/upload-artifact@v7
        with:
          path: "out/.config"
          include-hidden-files: true
          archive: false
