name: Build-Kernel

on:
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Cache Toolchains
      uses: actions/cache@v5
      with:
        path: toolchain
        key: ${{ runner.os }}-toolchains-r530567-v1

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl zip unzip bc bison flex build-essential python3

    - name: Build Kernel
      run:
        chmod +x build_kernel_zip.sh
        ./build_kernel_zip.sh

    - name: Upload Kernel (artifact)
      uses: actions/upload-artifact@v7
      with:
        name: "kernel-${{ github.sha }}"
        path: "*.zip"
